### ISSUE TITLE
Direct Cloud Run egress to VPC

### ISSUE THREAD

**Issue by sdrapkin** [kslifer/wordpress-on-gcp-free-tier#11]
Hi Kevin,

GCP just introduced https://cloud.google.com/blog/products/serverless/announcing-direct-vpc-egress-for-cloud-run

This should in theory allow you to put MySQL on a private-IP (#9), as long as your VPC-subnet can support at least 400 free IPs (ie. at least /23) for Cloud Run to grab...

**Comment by kslifer** [comment]
@sdrapkin good find and you're probably correct - will give it a shot at my earliest convenience!

**Comment by Mr-Lim** [comment]
Wondering if this will also allow removing the SSL MySQL connection from
WordPress, since traffic will now be routed via interval VPC. This might
also make migrating to MariaDB a bit easier (it's a pain to setup SSL), add
help squeeze just a bit more database performance out of our free tier
options.

**Comment by kslifer** [comment]
@sdrapkin Direct VPC Egress works beautifully - it's been tested and merged to master with a buch of other updates.
